extends Node
## Sound effects (autoload "Sfx"). Clips are generated by tools/make_sfx.py.
##
## - Everything pitched is in C major pentatonic (C D E G A): the clips are tuned to
##   it and bottle taps are repitched only to its notes, so overlapping sounds are
##   always consonant.
## - Every one-shot gets a small random volume offset so repeats don't sound
##   machine-gunned. Pitched clips only get a few cents of pitch drift, so they stay
##   in tune; noisy ones (splash) get more.
## - Each clip has a voice cap; the oldest voice is stolen past it.
## - The pour is a seamless loop repitched live as the target bottle fills, the way a
##   real bottle's note rises as the air column above the liquid shrinks.
## - Gameplay and UI go to separate buses; Master has a limiter as a safety net.
## - The mute setting is saved with the rest of the game's settings.

const SAVE_PATH := "user://save.cfg"
const DIR := "res://assets/sfx/"

## name: [bus, volume_db, max_voices, pitch_jitter, volume_jitter_db]
const CLIPS := {
	"select": ["SFX", 0.0, 2, 0.004, 1.0],
	"deselect": ["SFX", 0.0, 2, 0.004, 1.0],
	"place": ["SFX", 0.0, 3, 0.004, 1.5],
	"splash": ["SFX", 0.0, 2, 0.08, 1.5],
	"invalid": ["SFX", 0.0, 1, 0.0, 0.5],
	"cork": ["SFX", 0.0, 2, 0.0, 0.5],
	"win": ["SFX", 0.0, 1, 0.0, 0.0],
	"tap": ["UI", 0.0, 2, 0.004, 1.5],
	"hint": ["UI", 0.0, 1, 0.0, 0.0],
}
## Pour pitch from an empty to a full target bottle.
const POUR_PITCH_EMPTY := 0.82
const POUR_PITCH_FULL := 1.45

var muted := false:
	set(v):
		muted = v
		AudioServer.set_bus_mute(0, v)
		if v:
			stop_pour(0.0)

var _players := {}
var _pour: AudioStreamPlayer
var _pour_tween: Tween
var _pour_jitter := 1.0


func _ready() -> void:
	process_mode = Node.PROCESS_MODE_ALWAYS
	_setup_buses()
	for clip: String in CLIPS:
		var cfg: Array = CLIPS[clip]
		var p := AudioStreamPlayer.new()
		p.stream = load(DIR + clip + ".wav")
		p.bus = cfg[0]
		p.volume_db = cfg[1]
		p.max_polyphony = cfg[2]
		add_child(p)
		_players[clip] = p
	_pour = AudioStreamPlayer.new()
	_pour.stream = load(DIR + "pour_loop.wav")
	_pour.bus = "SFX"
	add_child(_pour)
	var cfg := ConfigFile.new()
	if cfg.load(SAVE_PATH) == OK:
		muted = bool(cfg.get_value("settings", "muted", false))


func _setup_buses() -> void:
	if AudioServer.get_bus_index("SFX") != -1:
		return
	var limiter := AudioEffectHardLimiter.new()
	limiter.ceiling_db = -0.5
	AudioServer.add_bus_effect(0, limiter)
	for bus: String in ["SFX", "UI"]:
		AudioServer.add_bus()
		var idx := AudioServer.bus_count - 1
		AudioServer.set_bus_name(idx, bus)
		AudioServer.set_bus_send(idx, "Master")
	# UI feedback stays under the gameplay sounds.
	AudioServer.set_bus_volume_db(AudioServer.get_bus_index("UI"), -2.0)


## Play a one-shot. `pitch` shifts the clip on top of its random jitter.
func play(clip: String, pitch := 1.0) -> void:
	if muted:
		return
	var p: AudioStreamPlayer = _players[clip]
	var cfg: Array = CLIPS[clip]
	var pj: float = cfg[3]
	var vj: float = cfg[4]
	p.pitch_scale = pitch * randf_range(1.0 - pj, 1.0 + pj)
	p.volume_db = cfg[1] + randf_range(-vj, vj)
	p.play()


## C major pentatonic, in semitones from C5 (the note the bottle clips are
## recorded on), high to low: G5 E5 D5 C5 A4 G4 E4.
const SCALE := [7, 4, 2, 0, -3, -5, -8]


## Pitch scale that moves a C-tuned clip by `semitones`.
static func note(semitones: int) -> float:
	return pow(2.0, semitones / 12.0)


## Pitch for tapping a bottle holding `level` of `capacity` units. Like struck
## water glasses, more liquid rings lower: empty is G5, full is G4. `steps_down`
## moves further down the scale (put-down sounds use one step lower than pick-up).
func bottle_pitch(level: int, capacity: int, steps_down := 0) -> float:
	var step := roundi(clampf(float(level) / capacity, 0.0, 1.0) * (SCALE.size() - 2))
	return note(SCALE[mini(step + steps_down, SCALE.size() - 1)])


func toggle_mute() -> void:
	muted = not muted
	var cfg := ConfigFile.new()
	cfg.load(SAVE_PATH)
	cfg.set_value("settings", "muted", muted)
	cfg.save(SAVE_PATH)


# ---------------------------------------------------------------- pour loop

func start_pour(fill: float) -> void:
	if muted:
		return
	_kill_pour_tween()
	_pour_jitter = randf_range(0.96, 1.04)
	set_pour_fill(fill)
	_pour.volume_db = -18.0
	_pour.play(randf() * _pour.stream.get_length())
	_pour_tween = create_tween()
	_pour_tween.tween_property(_pour, "volume_db", 0.0, 0.06)


## `fill` is the target bottle's level, 0 (empty) to 1 (full).
func set_pour_fill(fill: float) -> void:
	_pour.pitch_scale = lerpf(POUR_PITCH_EMPTY, POUR_PITCH_FULL, clampf(fill, 0.0, 1.0)) * _pour_jitter


func stop_pour(fade_time := 0.1) -> void:
	if not _pour.playing:
		return
	_kill_pour_tween()
	if fade_time <= 0.0:
		_pour.stop()
		return
	_pour_tween = create_tween()
	_pour_tween.tween_property(_pour, "volume_db", -40.0, fade_time).set_ease(Tween.EASE_IN)
	_pour_tween.tween_callback(_pour.stop)


func _kill_pour_tween() -> void:
	if _pour_tween and _pour_tween.is_valid():
		_pour_tween.kill()
